###
POST http://localhost:8080/doctors
Content-Type: application/json

{
  "firstName": "Nikita",
  "lastName": "Ivanov",
  "position": 3
}

###
GET http://localhost:8080/doctors

###
GET http://localhost:8080/doctors/1